# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      ## Setup
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install

      ## Lint
      - name: Run linters
        run: npm run lint

      ## Unit tests
      - name: Run unit tests
        run: npm run test:unit

        ## Build the source code
      - name: Build
        run: npm run build
      - name: Create 404 page
        run: cp ./dist/index.html ./dist/404.html
      - name: Upload build artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-artifact
          path: ./dist
          if-no-files-found: error # Ensures the step fails if no files are found in the specified path

      ## E2E test our built application
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run E2E tests
        env:
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      ## Deploy
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          # Ensure this step is explicitly configured to deploy the intended artifact
          # This field might need to be adjusted based on the action's expected configuration
          artifact_name: github-pages-artifact
